### PR TITLE
Svelte component UVU-113

### PR DESCRIPTION
**Pull request by nico-mikaela17**
Fixes UVU-113
Screenshot 2023-10-12 180242
image

### CODE REVIEW

**Review by Jchart3 — APPROVED** [review]
This looks really great!

**Comment by pcridesagain** [comment]
Reopening pull request

**Review by pcridesagain — CHANGES_REQUESTED** [review]
Looooking good! Let's chat in class about the "x" thing.

**Review by pcridesagain — APPROVED** [review]
forget the X

**Review by allison-baker — APPROVED** [review]
looks good!

**Pull request merged**
