### PR TITLE
Adding Svelte component files

### PR DESCRIPTION
**Pull request by Joonsung-Byun**
Fixes UVU-99
svelteComponent

### CODE REVIEW

**Review by macylau — APPROVED** [review]
looks good!

**Review by pcridesagain — CHANGES_REQUESTED** [review]
Super cool, but I want to request one change: it would be extra super cool if you only used one component that used a var, if statements, and props to define the size, that way when you create an instance of your component you just need to import one file and then set the size of the component on a single HTML element. You can follow the in class example to see how that works (look at the button component) We can also chat about it in class) https://svelte.dev/repl/f9aba0f00a93443e98d0f107770d41ac?version=4.2.1

**Review by cesrr — APPROVED** [review]
looks good

**Comment by Joonsung-Byun** [comment]
I fixed

**Review by lucypratt — APPROVED** [review]
The variable sizes look good!

**Review by pcridesagain — APPROVED** [review]

**Pull request merged**
