### PR TITLE
UVU-111 Svelte Component

### PR DESCRIPTION
**Pull request by macylau**
Fixes UVU-111
Screenshot 2023-10-12 at 8 49 25 PM

### CODE REVIEW

**Review by lucypratt — APPROVED** [review]
These look great!

**Review by pcridesagain — CHANGES_REQUESTED** [review]
Great work! But, I'm requesting changes cause this doesn't take advantage of svelte! Also, I'd like to see this implemented as a reusable component. Let's chat in class and I can explain myself and get you pointed in the right direction.

**Review by DianaAtzin — DISMISSED** [review]
The screenshot looks fantastic, but I encountered some difficulties when attempting to review your code. It might be a good idea to have a discussion with Patrick about your file settings and configurations to ensure a smoother code inspection process.

**Review by Joonsung-Byun — APPROVED** [review]
Looks good

**Review by Fernn10 — APPROVED** [review]
looks good!

**Review by pcridesagain — APPROVED** [review]

**Pull request merged**
