### PR TITLE
Gabbe pond   svelte component

### PR DESCRIPTION
**Pull request by gabbepond**

### CODE REVIEW

**Comment by gabbepond** [comment]
Sorry guys, it won't listen to my gitignore file so committed a lot of changes LOL.

**Review by willmiles00 — APPROVED** [review]
thats a lot of files

**Review by Mas-Dietrich — APPROVED** [review]
Glad you were able to figure out your problems with this one. Good work!

**Review by pcridesagain — CHANGES_REQUESTED** [review]
II’m sure the component is fantastic! But there is way to many lines of code committed to this PR to even begin to review it. We need to fix that before we move on. I can help you do that in class.

**Pull request closed without merging**
