### PR TITLE
Svelte Component-Cesar Espinoza-UVU-107

### PR DESCRIPTION
**Pull request by cesrr**
Fixes UVU-107
Screenshot 2023-10-12 at 6 05 27 PM

### CODE REVIEW

**Review by pcridesagain — APPROVED** [review]
I don't even know what the hell is going on here! JK, this is rad. Talk about clean code, this is great. Well done with the If statements so you can define all the props right in the instance. Super extensible.

**Review by awise0322 — APPROVED** [review]
Looks awesome 💯

**Review by gabbepond — APPROVED** [review]
Looks good

**Review by lucypratt — APPROVED** [review]
Nice!

**Comment by pcridesagain** [comment]
Closing pull request due to unresolvable conflicts

**Pull request closed without merging**
