### PR TITLE
Lucy Steckler   Svelte Component

### PR DESCRIPTION
**Pull request by lucypratt**
Fixes UVU-119
Screenshot 2023-10-12 210320

### CODE REVIEW

**Review by macylau — APPROVED** [review]
Looks good!

**Review by pcridesagain — CHANGES_REQUESTED** [review]
This is coming together! We just need to make one change so you can set one HTML component with properties to make this component resuable. A simple IF statement and variable should work. You can take a peak at the one we did in class, and we can also chat in class and I can get you pointed in the right direction. (https://svelte.dev/repl/f9aba0f00a93443e98d0f107770d41ac?version=4.2.1)

**Review by cesrr — APPROVED** [review]
nice

**Review by pcridesagain — APPROVED** [review]
approved!

**Pull request merged**
