### PR TITLE
Fixes UVU-121 Aidan Wiseman Svelte Component

### PR DESCRIPTION
**Pull request by awise0322**
Fixes UVU-121 
Holy cannoli I struggled

### CODE REVIEW

**Review by allison-baker — DISMISSED** [review]
I would remove all of the default files that Svelte puts in when you start a SvelteKit project, I can't find the files for your component

**Review by pcridesagain — CHANGES_REQUESTED** [review]
Holy cannoli! I like what I'm seeing here, but I'll be honest I don't know what is happening or how to run this correctly so let's chat in class and I can get you pointed in the right direction.

**Review by gabbepond — APPROVED** [review]
Looks good

**Review by cesrr — APPROVED** [review]
yessir

**Review by Joonsung-Byun — APPROVED** [review]
Looks good!

**Review by pcridesagain — APPROVED** [review]

**Pull request merged**
