### PR TITLE
Create Fixes UVU-120

### PR DESCRIPTION
**Pull request by X1Warrior**
SvelteComponent

### CODE REVIEW

**Review by willmiles00 — APPROVED** [review]
Let's get this bread!

**Review by pcridesagain — CHANGES_REQUESTED** [review]
We are missing the svelteyness and the reusable component! Let's chat in class and I can get you pointed in the right direction. The HTML is great, but lets make powerful!

**Review by X1Warrior — COMMENTED** [review]
Fixed the svelte components

**Review by nico-mikaela17 — APPROVED** [review]
Looks good!

**Review by Jchart3 — APPROVED** [review]
Looks good!

**Pull request merged**
