### PR TITLE
Mason Dietrich Svelte Component UVU-105

### PR DESCRIPTION
**Pull request by Mas-Dietrich**

### CODE REVIEW

**Review by gabbepond — APPROVED** [review]
Loooks good

**Review by pcridesagain — APPROVED** [review]
Well done (for code, not steaks). Love that you added props to define the instance of the component and even set the active tab! I was hoping to request changes, but I don't see any changes that need to be requested.

**Review by cesrr — APPROVED** [review]
good job

**Comment by pcridesagain** [comment]
Closing pull request due to unresolvable conflicts.

**Pull request closed without merging**
