### PR TITLE
diana/uvu-118-svelte-component

### PR DESCRIPTION
**Pull request by DianaAtzin**
diana/uvu-118-svelte-component

Fixes UVU-118

### CODE REVIEW

**Comment by DianaAtzin** [comment]
Screenshot 2023-10-13 at 2 02 40 AM

**Review by allison-baker — APPROVED** [review]
looks great!

**Review by pcridesagain — APPROVED** [review]
Applause! This is great, perfect use of the props to define a single instance of a component! I wanted to request changes on this but I there is not changes to be requested, great reusable component!!!

**Review by nico-mikaela17 — APPROVED** [review]
great job!

**Pull request merged**
