### PR TITLE
HTML/CSS ButtonsAuth-Component-DianaPutnam

### PR DESCRIPTION
**Pull request by DianaAtzin**
Fixes UVU-42

### CODE REVIEW

**Review by allison-baker — APPROVED** [review]
Looks good to me!

**Review by awise0322 — APPROVED** [review]
👌👌👌

**Review by nico-mikaela17 — APPROVED** [review]
I approve!

**Review by marklund117 — APPROVED** [review]
I like it

**Review by savannahcode — APPROVED** [review]
Looks great!

**Pull request closed without merging**
