### PR TITLE
Anferny Mendoza - Svelte Component UVU-115

### PR DESCRIPTION
**Pull request by Fernn10**
Fixes UVU-115
Screen Shot 2023-10-12 at 8 17 48 PM

### CODE REVIEW

**Review by macylau — APPROVED** [review]
looks good, approved

**Review by lucypratt — APPROVED** [review]
Looks great!

**Review by pcridesagain — CHANGES_REQUESTED** [review]
Chef's kiss! Almost, it's so close. I'd like to see you use one HTML instance (checkbox and radio) with props to generate each different style. You can follow the example we did in class to set this up, like I said you are so close! (lets chat in class and I can explain) https://svelte.dev/repl/f9aba0f00a93443e98d0f107770d41ac?version=4.2.1

**Comment by Fernn10** [comment]
> Chef's kiss! Almost, it's so close. I'd like to see you use one HTML instance (checkbox and radio) with props to generate each different style. You can follow the example we did in class to set this up, like I said you are so close! (lets chat in class and I can explain) https://svelte.dev/repl/f9aba0f00a93443e98d0f107770d41ac?version=4.2.1

Hi Professor! I have made the required changes(i hope lol). I refactored my code to uses props to generate each different style. Attached you will see the new image
Screen Shot 2023-10-26 at 3 18 34 PM

**Review by cesrr — APPROVED** [review]
nice

**Review by lucypratt — APPROVED** [review]
Changes look great!

**Review by pcridesagain — APPROVED** [review]

**Pull request merged**
