### PR TITLE
Al Baker Svelte Component

### PR DESCRIPTION
**Pull request by allison-baker**
Fixes UVU 98

### CODE REVIEW

**Comment by allison-baker** [comment]
svelte_component

**Review by pcridesagain — APPROVED** [review]
Beautiful. Well done of defining properties that can be used to select the type and size of the component when adding it to your page. I really wanted to Request Changes on this one but I can't.

**Comment by DocSmudge** [comment]
I love it! Nice work <3

**Review by DocSmudge — APPROVED** [review]
I love it! <3 nice work

**Review by tracecooney — COMMENTED** [review]
Looks good.

**Review by tracecooney — COMMENTED** [review]
Looks good.

**Pull request merged**
