### PR TITLE
Gabbe Pond   tailwind component UVU-77

### PR DESCRIPTION
**Pull request by gabbepond**
fixes UVU-77

### CODE REVIEW

**Review by Mas-Dietrich — APPROVED** [review]
very nice

**Review by DianaAtzin — APPROVED** [review]
Looking good

**Review by willmiles00 — APPROVED** [review]
Let's get this bread!

**Review by nico-mikaela17 — APPROVED** [review]
Slay

**Review by DianaAtzin — APPROVED** [review]
Good Job

**Review by awise0322 — APPROVED** [review]
Looks awesome

**Review by awise0322 — APPROVED** [review]
Looks awesome

**Review by Jchart3 — APPROVED** [review]

**Pull request closed without merging**
