### PR TITLE
UVU-114 Svelte Component

### PR DESCRIPTION
**Pull request by marklund117**
Fixes UVU-114

### CODE REVIEW

**Review by allison-baker — CHANGES_REQUESTED** [review]
Any way more of the code in the style block could be done with Tailwind instead? And I think we were supposed to have a separate file for the component and import it into the +page.svelte to practice importing a component

**Review by pcridesagain — CHANGES_REQUESTED** [review]
Coming together, but not quite a component yet. Let's chat in class and I can point you in the right direction to turn this guy into a super powerful, awesome sveltey, reusable component.

**Review by DianaAtzin — CHANGES_REQUESTED** [review]
Great work! From what I can gather, it seems like we should aim to maintain a consistent component style using Tailwind CSS, which will enhance reusability across our project. It might be a good idea to explore implementing this approach.

**Comment by pcridesagain** [comment]
Closing pull request due to unresolvable conflicts

**Pull request closed without merging**
