### PR TITLE
Fixes UVU-47

### PR DESCRIPTION
**Pull request by Fernn10**

### CODE REVIEW

**Review by lucypratt — APPROVED** [review]
Nice!

**Review by macylau — APPROVED** [review]
epic!

**Review by macylau — COMMENTED** [review]
I think we are creating components for dark mode for now, should the background color of the radio and the checkbox be none/ dark?

**Comment by Fernn10** [comment]
> I think we are creating components for dark mode for now, should the background color of the radio and the checkbox be none/ dark?

Yep, that is why I added a background of "black" to the labels :)

**Review by Joonsung-Byun — APPROVED** [review]
Nice!

**Pull request merged**
